import Head from "next/head";
import Image from "next/image";
import Wellcome from "../../components/Wellcome";
import Companies from "../../components/About";
import { SliderData } from "../../components/SliderData";
import Slider from "../../components/Slider";
import WhyOxo from "../../components/WhyOxo";
import Sentence from "../../components/Sentence";
import Footer from "../../components/Footer";
import Job from "../../components/Job";

export default function Home() {
  return (
    <>
      <Head>
        <title>OXO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Wellcome />
        <Companies />
        <Slider slides={SliderData} />
        <WhyOxo/>
        <Sentence/>
        <Job/>
        <Footer/>

      </main>
    </>
  );
}
